services:
  - type: web
    name: fitstyle-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
